apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: bhabasagar/spring-boot-docker.jar:latest  # The image pushed to the registry
        ports:
        - containerPort: 1009  # Port your Spring Boot app runs on
