apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1009  # The port your Spring Boot app listens on
  type: LoadBalancer  # Type LoadBalancer to expose the app externally in cloud environments
